workspace:
  base: /go
  path: src/github.com/isaactl/HelloWorld

pipeline:
  build:
    image: library/golang:1.8-alpine
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go get
      - go build

  publish/aws-china:
    image: isaactl/ecr
    region: cn-northwest-1
    repo: 233812712700.dkr.ecr.cn-northwest-1.amazonaws.com.cn/devnet/stripepay
    tags:
      - "${DRONE_COMMIT:0:7}"
      - latest

  publish:
    image: plugins/docker
    repo: isaactl/helloworld
    tag: latest
