apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        imagePullPolicy: Always
        image: "isaactl/helloworld:v1"
        ports:
        - containerPort: 80
        env:
        - name: "TEST_ENV"
          value: "What"
        resources:
          requests:
            memory: "64Mi"    # 64MiB
            cpu: "250m"       # 0.25cpu
          limits:
            memory: "128Mi"   # 128MiB
            cpu: "1000m"      # 1cpu
  selector:
    matchLabels:
      app: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworld
  type: ClusterIP